FROM ubuntu

RUN apt-get upgrade\
	&& apt-get update\
	&& apt-get install vim \
	&& apt-get instrall curl \
	&& cd /etc/init.d/nginx \     #进入nginx的安装目录
	&& ./nginx start \
	

 
 ./nginx start  #启动nginx容器
 pkill -9 nginx   #强行关闭
vim /etc/vim/vimrc

// docker run ubuntu -it  /bin/bash //以交互的形式运行docker

（--rm 就是在容器关闭之后,删除容器,节省内存）
